[package]
name = "queue53"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clearscreen = "3.0.0"
rpassword = "7.3.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
